
# ============================================================
# RESPONSE UTILITIES
# ============================================================


def clean_text(text):
    """
    Convert a response to clean text.
    """

    if text is None:
        return ""

    return str(text).strip()


# ============================================================
# STANDARD RESPONSE
# ============================================================

def build_response(
    answer,
    task=None,
    confidence=None,
    grounding=None,
    metadata=None,
):
    """
    Build a consistent response structure for the backend.

    Parameters
    ----------
    answer : str
        Final answer generated by the model.

    task : str, optional
        Task that produced the answer.

    confidence : float, optional
        Confidence value when available.

    grounding : list, optional
        Grounding boxes or other spatial information.

    metadata : dict, optional
        Additional task-specific information.
    """

    response = {
        "answer": clean_text(answer),
        "task": task,
    }

    if confidence is not None:
        response["confidence"] = confidence

    if grounding is not None:
        response["grounding"] = grounding

    if metadata is not None:
        response["metadata"] = metadata

    return response


# ============================================================
# ERROR RESPONSE
# ============================================================

def build_error_response(
    message,
    task=None,
):
    """
    Build a consistent error response.
    """

    return {
        "answer": "",
        "task": task,
        "error": clean_text(message),
    }


# ============================================================
# TASK RESULT NORMALIZATION
# ============================================================

def normalize_task_result(result, task=None):
    """
    Convert a task result into the standard backend response format.
    """

    if result is None:
        return build_response(
            answer="",
            task=task,
        )

    if isinstance(result, str):
        return build_response(
            answer=result,
            task=task,
        )

    if isinstance(result, dict):

        answer = result.get(
            "answer",
            result.get("response", ""),
        )

        return build_response(
            answer=answer,
            task=result.get("task", task),
            confidence=result.get("confidence"),
            grounding=result.get("grounding"),
            metadata=result.get("metadata"),
        )

    return build_response(
        answer=str(result),
        task=task,
    )


# ============================================================
# FRONTEND RESPONSE
# ============================================================

def build_frontend_response(
    answer,
    task,
    confidence=None,
    grounding=None,
    metadata=None,
):
    """
    Build the final response returned to the frontend.
    """

    response = {
        "success": True,
        "task": task,
        "answer": clean_text(answer),
    }

    if confidence is not None:
        response["confidence"] = confidence

    if grounding is not None:
        response["grounding"] = grounding

    if metadata is not None:
        response["metadata"] = metadata

    return response


# ============================================================
# FRONTEND ERROR
# ============================================================

def build_frontend_error(
    message,
    task=None,
):
    """
    Build a frontend-safe error response.
    """

    return {
        "success": False,
        "task": task,
        "answer": "",
        "error": clean_text(message),
    }

